name: Xcode - Build and Analyze

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: xcodebuild -sdk iphonesimulator16.2 -UseModernBuildSystem=NO -workspace iGoat-Swift/iGoat-Swift.xcodeproj/project.xcworkspace -scheme iGoat-Swift clean build CODE_SIGNING_ALLOWED=NO -configuration Release -arch x86_64
